### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by Wzb3422** [TheOreoPureMilk/ReadHub#3]
https://github.com/TheOreoPureMilk/ReadHub/blob/2f454d2768d57fc2ae6382299b07aefb7e5dfb2f/src/App.js#L10

为什么使用 HashRouter 呢

HashRouter 和 BrowserRouter 有什么区别

**Comment by TheOreoPureMilk** [comment]
我一开始是为了解决访问非根路由报404的问题去网上找了一下解决办法才发现的这个两个路由，理解并不深刻，，大概是这样：hash是因为请求的链接都是ip地址:端口/#/xxxx，因此请求的资源路径永远为/，相当于index.html，而其他的后端API接口都可以正常请求
BrowserRouter模式下请求的链接都是ip地址:端口/xxxx/xxxx，因此相当于每个URL都会访问一个不同的后端地址，如果后端没有覆盖到路由就会产生404错误。
大概是这样的想法
